(setq js3-mirror-mode t)
(autoload 'js3-mode "js3" nil t)
(add-to-list 'auto-mode-alist '("\\.js$" . js3-mode))
(add-hook 'js3-mode-hook
          (lambda ()
            (setq js3-indent-level 4)
            (setq js3-mode-dev-mode-p t)
            (setq js3-auto-indent t)
            (setq js3-enter-indents-newline t)
            (setq js3-indent-on-enter-key t)
            (when (require 'auto-complete nil t)
              (make-variable-buffer-local 'ac-source)
              (add-to-list 'ac-source 'ac-source-yasnippet)
              (auto-complete-mode t))))
